INSERT INTO TBL_CATEGORIA (ID, NOME) VALUES (1, 'Fabricação Própria');
INSERT INTO TBL_CATEGORIA (ID, NOME) VALUES (2, 'Nacional');
INSERT INTO TBL_CATEGORIA (ID, NOME) VALUES (3, 'Importado');
INSERT INTO TBL_CATEGORIA (ID, NOME) VALUES (4, 'Premium');