INSERT INTO TBL_CATEGORIA (NOME) VALUES ('Fabricação Própria');
INSERT INTO TBL_CATEGORIA (NOME) VALUES ('Nacional');
INSERT INTO TBL_CATEGORIA (NOME) VALUES ('Importado');
INSERT INTO TBL_CATEGORIA (NOME) VALUES ('Premium');